@startuml
!define DARKBLUE #F0F8FF
!define LIGHTBLUE #E0F2F7
!define GREEN #E6FFE6
!define ORANGE #FFFAF0
!define GREY #F5F5F5
!define RED #FFEEEE
!define PURPLE #E6E6FA
!define TEAL #E0FFFF

skinparam defaultFontName "Arial"
skinparam defaultFontSize 12
skinparam class {
    BackgroundColor White
    ArrowColor #2F4F4F
    BorderColor #2F4F4F
    FontColor #2F4F4F
}
skinparam package {
    BackgroundColor DARKBLUE
    BorderColor #1C405B
    FontColor #1C405B
}
skinparam stereotype {
    FontColor #6A5ACD
}

package "notifications_context" {

    package "application" {
        package "internal" {
            package "outboundservices" {
                package "email" {
                    interface SmtpNotificationSender <<(I, #CCCCFF) Interface>> {
                        + sendEmail(String, String, String): boolean
                        + sendEmail(String[], String, String): boolean
                        + sendHtmlEmail(String, String, String): boolean
                        + sendHtmlEmail(String[], String, String): boolean
                    }
                }
            }
        }
    }

    package "infrastructure" {
        package "services" {
            class SmtpNotificationSenderImpl <<(S, #ADD8E6) Service>> {
                - mailSender: JavaMailSender
                - fromEmail: String <<Value>>
                + SmtpNotificationSenderImpl(JavaMailSender)
                + sendEmail(String, String, String): boolean
                + sendEmail(String[], String, String): boolean
                + sendHtmlEmail(String, String, String): boolean
                + sendHtmlEmail(String[], String, String): boolean
            }
        }
    }
}




SmtpNotificationSenderImpl ..|> SmtpNotificationSender


@enduml